/*
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ducksms.client.api;

import com.ducksms.client.ApiException;
import com.ducksms.client.model.CreditBalance;
import com.ducksms.client.model.CreditHistory;
import com.ducksms.client.model.ErrorException;
import com.ducksms.client.model.ErrorInvalidRequest;
import com.ducksms.client.model.ErrorNotFound;
import com.ducksms.client.model.ErrorUnauthenticated;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CreditApi
 */
@Ignore
public class CreditApiTest {

    private final CreditApi api = new CreditApi();

    
    /**
     * Credit Balance
     *
     * Get available credit balance
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void creditBalanceTest() throws ApiException {
        CreditBalance response = api.creditBalance();

        // TODO: test validations
    }
    
    /**
     * Credit History
     *
     * Get all credit history
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void creditHistoryTest() throws ApiException {
        Integer page = null;
        String filterType = null;
        Integer filterSmsSmsid = null;
        CreditHistory response = api.creditHistory(page, filterType, filterSmsSmsid);

        // TODO: test validations
    }
    
}
