/*
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ducksms.client.api;

import com.ducksms.client.ApiException;
import com.ducksms.client.model.CreatedSmsSend;
import com.ducksms.client.model.ErrorException;
import com.ducksms.client.model.ErrorInvalidRequest;
import com.ducksms.client.model.ErrorUnauthenticated;
import com.ducksms.client.model.ErrorValidation;
import com.ducksms.client.model.PreviewSmsSend;
import com.ducksms.client.model.SmsSchema;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SmsApi
 */
@Ignore
public class SmsApiTest {

    private final SmsApi api = new SmsApi();

    
    /**
     * Send Sms
     *
     * Create a new sms
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void smsSendTest() throws ApiException {
        SmsSchema smsSchema = null;
        PreviewSmsSend response = api.smsSend(smsSchema);

        // TODO: test validations
    }
    
}
