/*
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ducksms.client.api;

import com.ducksms.client.ApiException;
import com.ducksms.client.model.CancelSmsSchedule;
import com.ducksms.client.model.ErrorException;
import com.ducksms.client.model.ErrorInvalidRequest;
import com.ducksms.client.model.ErrorNotFound;
import com.ducksms.client.model.ErrorUnauthenticated;
import com.ducksms.client.model.ListSmsSchedule;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SmsScheduleApi
 */
@Ignore
public class SmsScheduleApiTest {

    private final SmsScheduleApi api = new SmsScheduleApi();

    
    /**
     * Cancel Sms Schedule
     *
     * Cancel existing sms schedule
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelSmsScheduleTest() throws ApiException {
        String id = null;
        CancelSmsSchedule response = api.cancelSmsSchedule(id);

        // TODO: test validations
    }
    
    /**
     * List Sms Schedule
     *
     * List all the sms schedule
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSmsScheduleTest() throws ApiException {
        Integer page = null;
        String filterSenderName = null;
        String filterType = null;
        String filterMessageType = null;
        String filterStatus = null;
        ListSmsSchedule response = api.listSmsSchedule(page, filterSenderName, filterType, filterMessageType, filterStatus);

        // TODO: test validations
    }
    
}
