/*
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ducksms.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * CreatedSmsSend
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-20T08:24:59.680354Z[Etc/UTC]")
public class CreatedSmsSend {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Integer status;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private Map<String, List<String>> data = null;


  public CreatedSmsSend status(Integer status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "201", value = "")

  public Integer getStatus() {
    return status;
  }


  public void setStatus(Integer status) {
    this.status = status;
  }


  public CreatedSmsSend message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "The sms message is successfully scheduled", value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public CreatedSmsSend data(Map<String, List<String>> data) {
    
    this.data = data;
    return this;
  }

  public CreatedSmsSend putDataItem(String key, List<String> dataItem) {
    if (this.data == null) {
      this.data = new HashMap<>();
    }
    this.data.put(key, dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"smsid\":\"5006623151\",\"scheduled_at\":false,\"sender_id\":{\"name\":\"DUCKSMS\"},\"mobile_number\":[{\"number\":\"60131234567\",\"msgid\":2006553122},{\"number\":\"60131234562\",\"msgid\":7006553121}],\"credit\":{\"charge_per_sms\":1,\"charge_per_number\":1,\"charge\":1,\"balance\":986762,\"after\":986761},\"message\":{\"type\":\"ascii\",\"total\":1,\"length\":31,\"message\":\"RM0 DUCKSMS: Hello World, Good morning!\"},\"callback_url\":\"https://webhook.site/2a88e4b4-56f7-46ee-b3a4-2f05d8b8456e\",\"contains_special_characters\":false}", value = "")

  public Map<String, List<String>> getData() {
    return data;
  }


  public void setData(Map<String, List<String>> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatedSmsSend createdSmsSend = (CreatedSmsSend) o;
    return Objects.equals(this.status, createdSmsSend.status) &&
        Objects.equals(this.message, createdSmsSend.message) &&
        Objects.equals(this.data, createdSmsSend.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatedSmsSend {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

